import { CATEGORIES, type Category } from "@wordspy/types";

export type Difficulty = "easy" | "medium" | "hard";

export interface WordEntry {
  word: string;
  difficulty: Difficulty;
  enabled: boolean;
}

function pack(words: Array<[string, Difficulty]>): WordEntry[] {
  return words.map(([word, difficulty]) => ({ word, difficulty, enabled: true }));
}

/** Static word packs for the concrete categories. `random` is the union. */
export const WORD_PACKS: Record<Exclude<Category, "random">, WordEntry[]> = {
  // Famous foods from around the world.
  "world-food": pack([
    ["Pizza", "easy"],
    ["Sushi", "medium"],
    ["Pancake", "easy"],
    ["Burrito", "medium"],
    ["Ramen", "medium"],
    ["Popcorn", "easy"],
    ["Mango", "easy"],
    ["Waffle", "easy"],
    ["Burger", "easy"],
    ["Taco", "easy"],
    ["Donut", "easy"],
    ["Cupcake", "easy"],
    ["Spaghetti", "medium"],
    ["Hotdog", "easy"],
    ["Sandwich", "easy"],
    ["Noodles", "easy"],
    ["Dumpling", "medium"],
    ["Cheese", "easy"],
    ["Bacon", "easy"],
    ["Steak", "easy"],
    ["Salad", "easy"],
    ["Nachos", "medium"],
    ["Brownie", "easy"],
    ["Croissant", "medium"],
    ["Paella", "hard"],
    ["Sushi Roll", "medium"],
    ["Lasagna", "medium"],
    ["Kebab", "easy"],
    ["Pho", "hard"],
    ["Falafel", "medium"],
    ["Strawberry", "easy"],
    ["Pineapple", "easy"],
    ["Watermelon", "easy"],
    ["Cookie", "easy"],
    ["Pretzel", "medium"],
  ]),
  // Popular Indian dishes only.
  "indian-food": pack([
    ["Biryani", "easy"],
    ["Samosa", "easy"],
    ["Dosa", "medium"],
    ["Paneer", "easy"],
    ["Naan", "easy"],
    ["Curry", "medium"],
    ["Jalebi", "medium"],
    ["Idli", "medium"],
    ["Pakora", "medium"],
    ["Tandoori", "medium"],
    ["Lassi", "easy"],
    ["Tikka", "easy"],
    ["GulabJamun", "hard"],
    ["ButterChicken", "medium"],
    ["PaniPuri", "medium"],
    ["VadaPav", "medium"],
    ["CholeBhature", "hard"],
    ["Dal", "easy"],
    ["Chaat", "medium"],
    ["Rajma", "medium"],
    ["Pulao", "medium"],
    ["Korma", "hard"],
    ["Vindaloo", "hard"],
    ["Halwa", "medium"],
    ["Rasgulla", "hard"],
    ["Kheer", "medium"],
    ["Poha", "medium"],
    ["Upma", "hard"],
    ["Paratha", "easy"],
    ["Kulfi", "medium"],
  ]),
  // Internationally popular movies across genres and countries.
  "world-movies": pack([
    ["Titanic", "easy"],
    ["Inception", "hard"],
    ["Frozen", "easy"],
    ["Avatar", "easy"],
    ["Joker", "medium"],
    ["Matrix", "medium"],
    ["Jaws", "medium"],
    ["Coco", "easy"],
    ["Shrek", "easy"],
    ["Batman", "easy"],
    ["Interstellar", "hard"],
    ["Parasite", "medium"],
    ["Oppenheimer", "medium"],
    ["Barbie", "easy"],
    ["Dune", "medium"],
    ["Avengers", "easy"],
    ["Up", "easy"],
    ["Encanto", "easy"],
    ["Gladiator", "medium"],
    ["Rocky", "medium"],
    ["HarryPotter", "easy"],
    ["StarWars", "easy"],
    ["JurassicPark", "medium"],
    ["LionKing", "easy"],
    ["Goodfellas", "hard"],
    ["Whiplash", "hard"],
    ["Gravity", "medium"],
    ["Tenet", "hard"],
    ["Moana", "easy"],
  ]),
  // Popular Indian movies across languages.
  "indian-movies": pack([
    ["Sholay", "medium"],
    ["Dangal", "easy"],
    ["Lagaan", "medium"],
    ["Krrish", "medium"],
    ["Don", "easy"],
    ["Dhoom", "easy"],
    ["Bahubali", "easy"],
    ["RRR", "easy"],
    ["Padmaavat", "hard"],
    ["Barfi", "medium"],
    ["Singham", "medium"],
    ["Dabangg", "medium"],
    ["Devdas", "hard"],
    ["Andhadhun", "hard"],
    ["Drishyam", "medium"],
    ["Pathaan", "easy"],
    ["Jawan", "easy"],
    ["Animal", "medium"],
    ["Queen", "medium"],
    ["Pink", "easy"],
    ["ThreeIdiots", "easy"],
    ["Pushpa", "easy"],
    ["Kantara", "medium"],
    ["KGF", "easy"],
    ["Gully Boy", "medium"],
    ["Uri", "medium"],
    ["Zindagi", "hard"],
    ["Pk", "easy"],
    ["Chennai Express", "medium"],
    ["Vikram", "medium"],
  ]),
  animals: pack([
    ["Tiger", "easy"],
    ["Penguin", "easy"],
    ["Octopus", "medium"],
    ["Kangaroo", "medium"],
    ["Hedgehog", "medium"],
    ["Dolphin", "easy"],
    ["Chameleon", "hard"],
    ["Sloth", "easy"],
    ["Falcon", "medium"],
    ["Otter", "easy"],
    ["Elephant", "easy"],
    ["Giraffe", "easy"],
    ["Panda", "easy"],
    ["Koala", "easy"],
    ["Zebra", "easy"],
    ["Cheetah", "medium"],
    ["Rhino", "easy"],
    ["Hippo", "easy"],
    ["Crocodile", "medium"],
    ["Flamingo", "medium"],
    ["Peacock", "medium"],
    ["Squirrel", "easy"],
    ["Raccoon", "medium"],
    ["Wolf", "easy"],
    ["Fox", "easy"],
    ["Bear", "easy"],
    ["Owl", "easy"],
    ["Eagle", "easy"],
    ["Shark", "easy"],
    ["Whale", "easy"],
    ["Jellyfish", "medium"],
    ["Lobster", "medium"],
    ["Snail", "easy"],
    ["Butterfly", "easy"],
    ["Spider", "easy"],
    ["Scorpion", "medium"],
    ["Camel", "easy"],
    ["Llama", "easy"],
    ["Walrus", "medium"],
    ["Platypus", "hard"],
  ]),
  countries: pack([
    ["Brazil", "easy"],
    ["Japan", "easy"],
    ["Egypt", "medium"],
    ["Canada", "easy"],
    ["Norway", "medium"],
    ["Kenya", "medium"],
    ["Thailand", "medium"],
    ["Mexico", "easy"],
    ["Iceland", "hard"],
    ["Portugal", "medium"],
    ["France", "easy"],
    ["Germany", "easy"],
    ["Italy", "easy"],
    ["Spain", "easy"],
    ["India", "easy"],
    ["China", "easy"],
    ["Russia", "easy"],
    ["Greece", "easy"],
    ["Turkey", "medium"],
    ["Sweden", "medium"],
    ["Ireland", "medium"],
    ["Poland", "medium"],
    ["Austria", "medium"],
    ["Switzerland", "medium"],
    ["Morocco", "medium"],
    ["Nigeria", "medium"],
    ["Argentina", "medium"],
    ["Peru", "medium"],
    ["Chile", "medium"],
    ["Cuba", "medium"],
    ["Jamaica", "medium"],
    ["Vietnam", "medium"],
    ["Nepal", "medium"],
    ["Israel", "medium"],
    ["Finland", "medium"],
    ["Denmark", "medium"],
    ["Belgium", "medium"],
    ["Croatia", "hard"],
    ["Indonesia", "hard"],
    ["Mongolia", "hard"],
  ]),
  // Only widely-known sports kept (dropped obscure ones like curling/lacrosse).
  sports: pack([
    ["Football", "easy"],
    ["Tennis", "easy"],
    ["Cricket", "easy"],
    ["Boxing", "easy"],
    ["Hockey", "easy"],
    ["Cycling", "easy"],
    ["Basketball", "easy"],
    ["Baseball", "easy"],
    ["Golf", "easy"],
    ["Rugby", "medium"],
    ["Swimming", "easy"],
    ["Skiing", "easy"],
    ["Karate", "medium"],
    ["Wrestling", "medium"],
    ["Volleyball", "easy"],
    ["Badminton", "medium"],
    ["Marathon", "medium"],
    ["Gymnastics", "medium"],
    ["Skateboarding", "easy"],
    ["Surfing", "medium"],
    ["Bowling", "easy"],
    ["Archery", "medium"],
  ]),
  // Only everyday, widely-known tech kept (dropped niche jargon like microchip/hologram).
  technology: pack([
    ["Laptop", "easy"],
    ["Bluetooth", "medium"],
    ["Robot", "easy"],
    ["Keyboard", "easy"],
    ["Satellite", "medium"],
    ["Drone", "medium"],
    ["Browser", "medium"],
    ["Battery", "easy"],
    ["Webcam", "easy"],
    ["Smartphone", "easy"],
    ["Tablet", "easy"],
    ["Router", "medium"],
    ["Monitor", "easy"],
    ["Printer", "easy"],
    ["Mouse", "easy"],
    ["Speaker", "easy"],
    ["Headphone", "easy"],
    ["Charger", "easy"],
    ["Password", "easy"],
    ["Emoji", "easy"],
    ["Podcast", "easy"],
    ["Wifi", "easy"],
    ["Cloud", "medium"],
    ["Scanner", "easy"],
    ["Projector", "medium"],
    ["Microphone", "easy"],
    ["Smartwatch", "easy"],
  ]),
};

/** Enabled entries for a category; `random` unions every pack. */
export function enabledWords(category: Category): WordEntry[] {
  if (category === "random") {
    return (Object.keys(WORD_PACKS) as Array<Exclude<Category, "random">>)
      .flatMap((c) => WORD_PACKS[c])
      .filter((w) => w.enabled);
  }
  return WORD_PACKS[category].filter((w) => w.enabled);
}

/** Sanity guard used by tests: every concrete category has words. */
export const CONCRETE_CATEGORIES = CATEGORIES.filter((c) => c !== "random");
