import { CATEGORIES, type Category } from "@wordspy/types";

export type Difficulty = "easy" | "medium" | "hard";

export interface WordEntry {
  word: string;
  difficulty: Difficulty;
  enabled: boolean;
}

function pack(words: Array<[string, Difficulty]>): WordEntry[] {
  return words.map(([word, difficulty]) => ({ word, difficulty, enabled: true }));
}

/** Static word packs for the six concrete categories. `random` is the union. */
export const WORD_PACKS: Record<Exclude<Category, "random">, WordEntry[]> = {
  food: pack([
    ["Pizza", "easy"],
    ["Sushi", "medium"],
    ["Pancake", "easy"],
    ["Burrito", "medium"],
    ["Ramen", "medium"],
    ["Croissant", "hard"],
    ["Popcorn", "easy"],
    ["Lasagna", "medium"],
    ["Mango", "easy"],
    ["Waffle", "easy"],
    ["Burger", "easy"],
    ["Taco", "easy"],
    ["Donut", "easy"],
    ["Cupcake", "easy"],
    ["Spaghetti", "medium"],
    ["Hotdog", "easy"],
    ["Sandwich", "easy"],
    ["Noodles", "easy"],
    ["Dumpling", "medium"],
    ["Omelette", "medium"],
    ["Cheese", "easy"],
    ["Yogurt", "easy"],
    ["Cereal", "easy"],
    ["Bacon", "easy"],
    ["Steak", "easy"],
    ["Salad", "easy"],
    ["Curry", "medium"],
    ["Falafel", "hard"],
    ["Nachos", "medium"],
    ["Pretzel", "medium"],
    ["Brownie", "easy"],
    ["Muffin", "easy"],
    ["Bagel", "medium"],
    ["Pickle", "easy"],
    ["Avocado", "medium"],
    ["Strawberry", "easy"],
    ["Pineapple", "easy"],
    ["Watermelon", "easy"],
    ["Cookie", "easy"],
    ["Tiramisu", "hard"],
  ]),
  movies: pack([
    ["Titanic", "easy"],
    ["Inception", "hard"],
    ["Frozen", "easy"],
    ["Gladiator", "medium"],
    ["Avatar", "easy"],
    ["Joker", "medium"],
    ["Matrix", "medium"],
    ["Up", "easy"],
    ["Jaws", "medium"],
    ["Coco", "easy"],
    ["Shrek", "easy"],
    ["Batman", "easy"],
    ["Rocky", "medium"],
    ["Alien", "medium"],
    ["Cars", "easy"],
    ["Moana", "easy"],
    ["Encanto", "easy"],
    ["Aladdin", "easy"],
    ["Tarzan", "medium"],
    ["Dumbo", "medium"],
    ["Gravity", "medium"],
    ["Interstellar", "hard"],
    ["Braveheart", "medium"],
    ["Ratatouille", "hard"],
    ["Goodfellas", "hard"],
    ["Psycho", "medium"],
    ["Whiplash", "hard"],
    ["Parasite", "medium"],
    ["Oppenheimer", "medium"],
    ["Barbie", "easy"],
    ["Dune", "medium"],
    ["Tenet", "hard"],
    ["Avengers", "easy"],
    ["Deadpool", "medium"],
    ["Twister", "medium"],
    ["Bambi", "medium"],
    ["Halloween", "easy"],
    ["Mulan", "easy"],
    ["Tangled", "medium"],
    ["Spirited", "hard"],
  ]),
  animals: pack([
    ["Tiger", "easy"],
    ["Penguin", "easy"],
    ["Octopus", "medium"],
    ["Kangaroo", "medium"],
    ["Hedgehog", "medium"],
    ["Dolphin", "easy"],
    ["Chameleon", "hard"],
    ["Sloth", "easy"],
    ["Falcon", "medium"],
    ["Otter", "easy"],
    ["Elephant", "easy"],
    ["Giraffe", "easy"],
    ["Panda", "easy"],
    ["Koala", "easy"],
    ["Zebra", "easy"],
    ["Cheetah", "medium"],
    ["Rhino", "easy"],
    ["Hippo", "easy"],
    ["Crocodile", "medium"],
    ["Flamingo", "medium"],
    ["Peacock", "medium"],
    ["Squirrel", "easy"],
    ["Raccoon", "medium"],
    ["Wolf", "easy"],
    ["Fox", "easy"],
    ["Bear", "easy"],
    ["Owl", "easy"],
    ["Eagle", "easy"],
    ["Shark", "easy"],
    ["Whale", "easy"],
    ["Jellyfish", "medium"],
    ["Lobster", "medium"],
    ["Snail", "easy"],
    ["Butterfly", "easy"],
    ["Spider", "easy"],
    ["Scorpion", "medium"],
    ["Camel", "easy"],
    ["Llama", "easy"],
    ["Walrus", "medium"],
    ["Platypus", "hard"],
  ]),
  countries: pack([
    ["Brazil", "easy"],
    ["Japan", "easy"],
    ["Egypt", "medium"],
    ["Canada", "easy"],
    ["Norway", "medium"],
    ["Kenya", "medium"],
    ["Thailand", "medium"],
    ["Mexico", "easy"],
    ["Iceland", "hard"],
    ["Portugal", "medium"],
    ["France", "easy"],
    ["Germany", "easy"],
    ["Italy", "easy"],
    ["Spain", "easy"],
    ["India", "easy"],
    ["China", "easy"],
    ["Russia", "easy"],
    ["Greece", "easy"],
    ["Turkey", "medium"],
    ["Sweden", "medium"],
    ["Ireland", "medium"],
    ["Poland", "medium"],
    ["Austria", "medium"],
    ["Switzerland", "medium"],
    ["Morocco", "medium"],
    ["Nigeria", "medium"],
    ["Argentina", "medium"],
    ["Peru", "medium"],
    ["Chile", "medium"],
    ["Cuba", "medium"],
    ["Jamaica", "medium"],
    ["Vietnam", "medium"],
    ["Nepal", "medium"],
    ["Israel", "medium"],
    ["Finland", "medium"],
    ["Denmark", "medium"],
    ["Belgium", "medium"],
    ["Croatia", "hard"],
    ["Indonesia", "hard"],
    ["Mongolia", "hard"],
  ]),
  sports: pack([
    ["Football", "easy"],
    ["Tennis", "easy"],
    ["Cricket", "medium"],
    ["Boxing", "easy"],
    ["Surfing", "medium"],
    ["Archery", "hard"],
    ["Hockey", "medium"],
    ["Cycling", "easy"],
    ["Bowling", "easy"],
    ["Rowing", "medium"],
    ["Basketball", "easy"],
    ["Baseball", "easy"],
    ["Golf", "easy"],
    ["Rugby", "medium"],
    ["Swimming", "easy"],
    ["Skiing", "easy"],
    ["Skating", "easy"],
    ["Karate", "medium"],
    ["Judo", "medium"],
    ["Fencing", "hard"],
    ["Wrestling", "medium"],
    ["Volleyball", "easy"],
    ["Badminton", "medium"],
    ["Snooker", "hard"],
    ["Darts", "medium"],
    ["Climbing", "medium"],
    ["Diving", "medium"],
    ["Sailing", "medium"],
    ["Kayaking", "hard"],
    ["Marathon", "medium"],
    ["Sprint", "easy"],
    ["Gymnastics", "medium"],
    ["Polo", "hard"],
    ["Curling", "hard"],
    ["Snowboarding", "medium"],
    ["Skateboarding", "easy"],
    ["Handball", "medium"],
    ["Squash", "hard"],
    ["Triathlon", "hard"],
    ["Lacrosse", "hard"],
  ]),
  technology: pack([
    ["Laptop", "easy"],
    ["Bluetooth", "medium"],
    ["Robot", "easy"],
    ["Keyboard", "easy"],
    ["Satellite", "hard"],
    ["Drone", "medium"],
    ["Browser", "medium"],
    ["Battery", "easy"],
    ["Firewall", "hard"],
    ["Webcam", "easy"],
    ["Smartphone", "easy"],
    ["Tablet", "easy"],
    ["Router", "medium"],
    ["Server", "medium"],
    ["Monitor", "easy"],
    ["Printer", "easy"],
    ["Mouse", "easy"],
    ["Speaker", "easy"],
    ["Headphone", "easy"],
    ["Charger", "easy"],
    ["Joystick", "medium"],
    ["Microchip", "hard"],
    ["Hologram", "hard"],
    ["Algorithm", "hard"],
    ["Database", "medium"],
    ["Password", "easy"],
    ["Hashtag", "easy"],
    ["Emoji", "easy"],
    ["Podcast", "easy"],
    ["Wifi", "easy"],
    ["Cloud", "medium"],
    ["Cursor", "easy"],
    ["Pixel", "medium"],
    ["Antenna", "medium"],
    ["Modem", "medium"],
    ["Scanner", "easy"],
    ["Projector", "medium"],
    ["Microphone", "easy"],
    ["Smartwatch", "easy"],
    ["Hardware", "medium"],
  ]),
};

/** Enabled entries for a category; `random` unions every pack. */
export function enabledWords(category: Category): WordEntry[] {
  if (category === "random") {
    return (Object.keys(WORD_PACKS) as Array<Exclude<Category, "random">>)
      .flatMap((c) => WORD_PACKS[c])
      .filter((w) => w.enabled);
  }
  return WORD_PACKS[category].filter((w) => w.enabled);
}

/** Sanity guard used by tests: every concrete category has words. */
export const CONCRETE_CATEGORIES = CATEGORIES.filter((c) => c !== "random");
